### PR TITLE
Fix signing keys and txs folder on remote

### PR DESCRIPTION
**Pull request by samuelWilliams99**
When operating with a remote CLI, I noticed a few issues:
- Balancing transactions required the signing keys file to be on the remote machine, but they weren't written until submission
- The `txs` folder is always created on the local machine, whereas, if we're running remote, it needs to be on the remote machine
- Various files and directories are created in non-optimum places

### CODE REVIEW

**Review by gege251 — APPROVED** [review]
LGTM.
I assume you have already checked with a real remote server.
Might not really worth the effort, but I think we could extend the MockContract testing framework so that it checks for files on cli calls, so we don't run into the same kind of trouble after a refactoring.

**Comment by samuelWilliams99** [comment]
Yep I've tested on real remote. I havent however tested on local, as I dont have that environment readily available. I don't expect these changes to even remotely affect Local, but it might be worth checking if you know of a quick way to do so?

**Comment by gege251** [comment]
I'll just check them myself

**Comment by gege251** [comment]
We already have that mock file system here: https://github.com/mlabs-haskell/bot-plutus-interface/blob/master/test/Spec/MockContract.hs#L198 but it doesn't handle uploadDir yet

**Comment by gege251** [comment]
@samuelWilliams99 Did a few tests with the examples on the local environment, it looks good.

**Comment by samuelWilliams99** [comment]
> cli call parsing could get a bit tedious

Depends, we dont need to parse the whole thing. theres a set of specific flags that are followed by a path, we can just look for those then grab the next thing up to a space (or quoted)

**Comment by samuelWilliams99** [comment]
I think the tests would probably go best with the `tx delete` changes, as we can generalise to ensure that works as well

**Comment by samuelWilliams99** [comment]
Or, at the very least, a new ticket. This one is a bug fix

**Comment by samuelWilliams99** [comment]
Going to handle the mock file system improvements in #65

**Pull request merged**
